### ISSUE TITLE
Built binary contains reference to build path

### ISSUE THREAD

**Issue by poscat0x04** [digital-asset/ghcide#330]
I got this error when I tried to run a binary copied from another machine.
```
ghcide: /build/.stack/programs/x86_64-linux/ghc-tinfo6-8.6.5/lib/ghc-8.6.5/settings: openFile: does not exist (No such file or directory)
```
It seems that ghcide contains some reference to the `.stack` folder on the build machine (/build is the build root) which makes it impossible to be distributed as a binary package.

**Comment by poscat0x04** [comment]
I think haskell-ide-engine has a similar issue:
https://github.com/haskell/haskell-ide-engine/issues/400

**Comment by fendor** [comment]
Ghcide depends on `ghc-paths` (https://github.com/digital-asset/ghcide/blob/master/exe/Main.hs#L55) to obtain the ghc libdir, which compiles this path into the executable.
In `haskell-ide-engine`, it was solved by selecting, based on the cradle, the right `ghc` executable and executing `ghc --print-libdir` to obtain the libdir at run-time.

**Comment by poscat0x04** [comment]
I see. Thanks for the info.

**Comment by poscat0x04** [comment]
I think this problem has been solved with the use of hie-bios. Closing.

**Comment by ndmitchell** [comment]
It's still broken, but https://github.com/digital-asset/ghcide/issues/387 tracks the issue to, so lets use that one.
